# Generated by Django 5.0.1 on 2024-01-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorregister',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='Número de telefone'),
        ),
    ]
