# Generated by Django 5.0.1 on 2024-01-22 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_authorregister_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorregister',
            options={'verbose_name': 'Authors', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterField(
            model_name='authorregister',
            name='age',
            field=models.IntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='authorregister',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='authorregister',
            name='current_city',
            field=models.CharField(choices=[('Acre', 'Acre'), ('Alagoas', 'Alagoas'), ('Amapá', 'Amapá'), ('Amazonas', 'Amazonas'), ('Bahia', 'Bahia'), ('Ceará', 'Ceará'), ('Distrito Federal', 'Distrito Federal'), ('Espírito Santo', 'Espírito Santo'), ('Goiás', 'Goiás'), ('Maranhão', 'Maranhão'), ('Mato Grosso', 'Mato Grosso'), ('Mato Grosso', 'Mato Grosso'), ('Mato Grosso', 'Mato Grosso'), ('Mato Grosso', 'Mato Grosso'), ('Mato Grosso', 'Mato Grosso'), ('Mato Grosso do Sul', 'Mato Grosso do Sul'), ('Minas Gerais', 'Minas Gerais'), ('Pará ', 'Pará '), ('Paraíba', 'Paraíba'), ('Paraná', 'Paraná'), ('Pernambuco', 'Pernambuco'), ('Piauí', 'Piauí'), ('Rio de Janeiro', 'Rio de Janeiro'), ('Rio Grande do Norte', 'Rio Grande do Norte'), ('Rio Grande do Sul', 'Rio Grande do Sul'), ('Rondônia', 'Rondônia'), ('Roraima', 'Roraima'), ('Santa Catarina', 'Santa Catarina'), ('São Paulo', 'São Paulo'), ('Sergipe', 'Sergipe'), ('Tocantins', 'Tocantins')], default='', max_length=19, verbose_name='Current City'),
        ),
        migrations.AlterField(
            model_name='authorregister',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Profile Description'),
        ),
        migrations.AlterField(
            model_name='authorregister',
            name='hometown',
            field=models.CharField(choices=[('Acre', 'Acre'), ('Alagoas', 'Alagoas'), ('Amapá', 'Amapá'), ('Amazonas', 'Amazonas'), ('Bahia', 'Bahia'), ('Ceará', 'Ceará'), ('Distrito Federal', 'Distrito Federal'), ('Espírito Santo', 'Espírito Santo'), ('Goiás', 'Goiás'), ('Maranhão', 'Maranhão'), ('Mato Grosso', 'Mato Grosso'), ('Mato Grosso', 'Mato Grosso'), ('Mato Grosso', 'Mato Grosso'), ('Mato Grosso', 'Mato Grosso'), ('Mato Grosso', 'Mato Grosso'), ('Mato Grosso do Sul', 'Mato Grosso do Sul'), ('Minas Gerais', 'Minas Gerais'), ('Pará ', 'Pará '), ('Paraíba', 'Paraíba'), ('Paraná', 'Paraná'), ('Pernambuco', 'Pernambuco'), ('Piauí', 'Piauí'), ('Rio de Janeiro', 'Rio de Janeiro'), ('Rio Grande do Norte', 'Rio Grande do Norte'), ('Rio Grande do Sul', 'Rio Grande do Sul'), ('Rondônia', 'Rondônia'), ('Roraima', 'Roraima'), ('Santa Catarina', 'Santa Catarina'), ('São Paulo', 'São Paulo'), ('Sergipe', 'Sergipe'), ('Tocantins', 'Tocantins')], max_length=19, verbose_name='Hometown'),
        ),
        migrations.AlterField(
            model_name='authorregister',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active?'),
        ),
        migrations.AlterField(
            model_name='authorregister',
            name='marital_status',
            field=models.CharField(choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viúvo', 'Viúvo')], max_length=15, verbose_name='Marital Status'),
        ),
        migrations.AlterField(
            model_name='authorregister',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='authorregister',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='authors/covers/profile', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='authorregister',
            name='profile_status',
            field=models.CharField(choices=[('Público', 'Público'), ('Privado', 'Privado')], max_length=8, verbose_name='Profile Status'),
        ),
        migrations.AlterField(
            model_name='authorregister',
            name='sex',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=10, verbose_name='Sex'),
        ),
    ]
