# Generated by Django 5.0.1 on 2024-01-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/covers/%Y/%m/%d', verbose_name='Image'),
        ),
    ]
