# Generated by Django 5.0.1 on 2024-01-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Is published'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='qty_read',
            field=models.IntegerField(default=0, verbose_name='Qty read'),
        ),
    ]
